repositories {
    maven {
        url "https://jitpack.io/"
        name "Jitpack"
    }
}

loom {
    accessWidenerPath = file("src/main/resources/shearapi-registries.accesswidener")
}

dependencies {
    compileOnly project(path: ":shearapi-compile-fml", configuration: "namedElements")
    api project(path: ":shearapi-runtime", configuration: "namedElements")
    api project(path: ":shearapi-event", configuration: "namedElements")
    modImplementation "com.github.Chocohead:Fabric-ASM:v${project.fabric_asm_version}"
}
