loom {
    accessWidenerPath = file("src/main/resources/shearapi-registry-datamaps.accesswidener")
}

dependencies {
//    api project(path: ":shearapi-conditions", configuration: "namedElements")
    api project(path: ":shearapi-registries", configuration: "namedElements")
    api project(path: ":shearapi-network", configuration: "namedElements")
    api project(path: ":shearapi-resource", configuration: "namedElements")
}
